import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import {
	ApolloClient,
	InMemoryCache,
	gql
} from "@apollo/client";

import Header from '@components/Header'
import styles from '@styles/Home.module.scss'
import Container from '@components/Container'
import Button from '@components/Button'


export default function Home({ products }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://app.snipcart.com" />
				<link rel="preconnect" href="https://cdn.snipcart.com" />
				<link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.3.1/default/snipcart.css" />
			</Head>

			<Header />
			<main className={styles.main}>

				<Container>
					<h1>JPeex</h1>
					<h2>Available Cards</h2>
					<ul className={styles.products}>
						{products.map(product => {
							const { featuredImage } = product;

							return (
								<li key={product.id}>
									<Image
										width={featuredImage.mediaDetails.width}
										height={featuredImage.mediaDetails.height}
										src={featuredImage.sourceUrl}
										alt={featuredImage.altText} />
									<h3 className={styles.productTitle}>{product.title}</h3>
									<p className={styles.productPrice}>
										${product.productPrice}
									</p>
									<p>
										<Button
											className="snipcart-add-item"
											data-item-id={product.id}
											data-item-price={product.productPrice}
											data-item-url="/"
											data-item-description=""
											data-item-image={featuredImage.sourceUrl}
											data-item-name={product.title}
										>Add to Cart</Button>
									</p>
								</li>
							)
						})}
					</ul>
				</Container>
			</main>

			<footer className={styles.footer}>
				&copy; JPeex {new Date().getFullYear()}
			</footer>
			<Script src="https://cdn.snipcart.com/themes/v3.3.1/default/snipcart.js" />
			<div hidden id="snipcart" data-api-key="ZmJmOGQyYTAtNmFmYy00N2EwLTk0ODUtOGIyNjE5ODc0MDNjNjM3ODA3NzM1NjI4Nzk0NjQ5" />
		</div>
	)
}

export async function getStaticProps() {
	const client = new ApolloClient({
		uri: 'https://test.jpeex.com/graphql',
		cache: new InMemoryCache()
	});

	const response = await client.query({
		query: gql`
		query AllProducts {
			products {
				edges {
				node {
					id
					content
					title
					uri
					slug
					product {
						productPrice
						fieldGroupName
					}
					featuredImage {
						node {
								altText
								sourceUrl
								mediaDetails {
								height
								width
								}
							}
						}
					}
				}
			}
		}				  
		`
	})

	const products = response.data.products.edges.map(({ node }) => {
		const data = {
			...node,
			...node.product,
			featuredImage: {
				...node.featuredImage.node
			}
		}
		return data;
	});
	console.log(products);
	return {
		props: {
			products
		}
	}
}